/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKBNO085_SPI_LIBRARY_H
#define _MOCKBNO085_SPI_LIBRARY_H

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>
#include "BNO085_SPI_Library.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockBNO085_SPI_Library_Init(void);
void MockBNO085_SPI_Library_Destroy(void);
void MockBNO085_SPI_Library_Verify(void);




#define register_Sensor_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("register_Sensor requires _Ignore (not AndReturn)");
#define register_Sensor_Ignore() register_Sensor_CMockIgnore()
void register_Sensor_CMockIgnore(void);
#define register_Sensor_StopIgnore() register_Sensor_CMockStopIgnore()
void register_Sensor_CMockStopIgnore(void);
#define register_Sensor_ExpectAndReturn(sensor, sensor_number, sensor_CSN_Pin, sensor_CSN_Port, sensor_INTN_Pin, sensor_INTN_Port, sensor_RSTN_Pin, sensor_RSTN_Port, cmock_retval) TEST_FAIL_MESSAGE("register_Sensor requires _Expect (not AndReturn)");
#define register_Sensor_Expect(sensor, sensor_number, sensor_CSN_Pin, sensor_CSN_Port, sensor_INTN_Pin, sensor_INTN_Port, sensor_RSTN_Pin, sensor_RSTN_Port) register_Sensor_CMockExpect(__LINE__, sensor, sensor_number, sensor_CSN_Pin, sensor_CSN_Port, sensor_INTN_Pin, sensor_INTN_Port, sensor_RSTN_Pin, sensor_RSTN_Port)
void register_Sensor_CMockExpect(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t sensor_number, uint16_t sensor_CSN_Pin, GPIO_TypeDef* sensor_CSN_Port, uint16_t sensor_INTN_Pin, GPIO_TypeDef* sensor_INTN_Port, uint16_t sensor_RSTN_Pin, GPIO_TypeDef* sensor_RSTN_Port);
typedef void (* CMOCK_register_Sensor_CALLBACK)(sensor_meta* sensor, uint8_t sensor_number, uint16_t sensor_CSN_Pin, GPIO_TypeDef* sensor_CSN_Port, uint16_t sensor_INTN_Pin, GPIO_TypeDef* sensor_INTN_Port, uint16_t sensor_RSTN_Pin, GPIO_TypeDef* sensor_RSTN_Port, int cmock_num_calls);
void register_Sensor_AddCallback(CMOCK_register_Sensor_CALLBACK Callback);
void register_Sensor_Stub(CMOCK_register_Sensor_CALLBACK Callback);
#define register_Sensor_StubWithCallback register_Sensor_Stub
int register_Sensor_CallCount(void);
#define clear_init_Message_IMU_Ignore() TEST_FAIL_MESSAGE("clear_init_Message_IMU requires _IgnoreAndReturn");
#define clear_init_Message_IMU_IgnoreAndReturn(cmock_retval) clear_init_Message_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void clear_init_Message_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define clear_init_Message_IMU_StopIgnore() clear_init_Message_IMU_CMockStopIgnore()
void clear_init_Message_IMU_CMockStopIgnore(void);
#define clear_init_Message_IMU_Expect(sensor) TEST_FAIL_MESSAGE("clear_init_Message_IMU requires _ExpectAndReturn");
#define clear_init_Message_IMU_ExpectAndReturn(sensor, cmock_retval) clear_init_Message_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void clear_init_Message_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_clear_init_Message_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void clear_init_Message_IMU_AddCallback(CMOCK_clear_init_Message_IMU_CALLBACK Callback);
void clear_init_Message_IMU_Stub(CMOCK_clear_init_Message_IMU_CALLBACK Callback);
#define clear_init_Message_IMU_StubWithCallback clear_init_Message_IMU_Stub
int clear_init_Message_IMU_CallCount(void);
#define hardreset_IMU_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hardreset_IMU requires _Ignore (not AndReturn)");
#define hardreset_IMU_Ignore() hardreset_IMU_CMockIgnore()
void hardreset_IMU_CMockIgnore(void);
#define hardreset_IMU_StopIgnore() hardreset_IMU_CMockStopIgnore()
void hardreset_IMU_CMockStopIgnore(void);
#define hardreset_IMU_ExpectAndReturn(sensor, cmock_retval) TEST_FAIL_MESSAGE("hardreset_IMU requires _Expect (not AndReturn)");
#define hardreset_IMU_Expect(sensor) hardreset_IMU_CMockExpect(__LINE__, sensor)
void hardreset_IMU_CMockExpect(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor);
typedef void (* CMOCK_hardreset_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void hardreset_IMU_AddCallback(CMOCK_hardreset_IMU_CALLBACK Callback);
void hardreset_IMU_Stub(CMOCK_hardreset_IMU_CALLBACK Callback);
#define hardreset_IMU_StubWithCallback hardreset_IMU_Stub
int hardreset_IMU_CallCount(void);
#define softreset_IMU_Ignore() TEST_FAIL_MESSAGE("softreset_IMU requires _IgnoreAndReturn");
#define softreset_IMU_IgnoreAndReturn(cmock_retval) softreset_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void softreset_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define softreset_IMU_StopIgnore() softreset_IMU_CMockStopIgnore()
void softreset_IMU_CMockStopIgnore(void);
#define softreset_IMU_Expect(sensor) TEST_FAIL_MESSAGE("softreset_IMU requires _ExpectAndReturn");
#define softreset_IMU_ExpectAndReturn(sensor, cmock_retval) softreset_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void softreset_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_softreset_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void softreset_IMU_AddCallback(CMOCK_softreset_IMU_CALLBACK Callback);
void softreset_IMU_Stub(CMOCK_softreset_IMU_CALLBACK Callback);
#define softreset_IMU_StubWithCallback softreset_IMU_Stub
int softreset_IMU_CallCount(void);
#define softresetDCD_IMU_Ignore() TEST_FAIL_MESSAGE("softresetDCD_IMU requires _IgnoreAndReturn");
#define softresetDCD_IMU_IgnoreAndReturn(cmock_retval) softresetDCD_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void softresetDCD_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define softresetDCD_IMU_StopIgnore() softresetDCD_IMU_CMockStopIgnore()
void softresetDCD_IMU_CMockStopIgnore(void);
#define softresetDCD_IMU_Expect(sensor) TEST_FAIL_MESSAGE("softresetDCD_IMU requires _ExpectAndReturn");
#define softresetDCD_IMU_ExpectAndReturn(sensor, cmock_retval) softresetDCD_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void softresetDCD_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_softresetDCD_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void softresetDCD_IMU_AddCallback(CMOCK_softresetDCD_IMU_CALLBACK Callback);
void softresetDCD_IMU_Stub(CMOCK_softresetDCD_IMU_CALLBACK Callback);
#define softresetDCD_IMU_StubWithCallback softresetDCD_IMU_Stub
int softresetDCD_IMU_CallCount(void);
#define get_and_clear_Reset_Status_Ignore() TEST_FAIL_MESSAGE("get_and_clear_Reset_Status requires _IgnoreAndReturn");
#define get_and_clear_Reset_Status_IgnoreAndReturn(cmock_retval) get_and_clear_Reset_Status_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_and_clear_Reset_Status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define get_and_clear_Reset_Status_StopIgnore() get_and_clear_Reset_Status_CMockStopIgnore()
void get_and_clear_Reset_Status_CMockStopIgnore(void);
#define get_and_clear_Reset_Status_Expect(sensor) TEST_FAIL_MESSAGE("get_and_clear_Reset_Status requires _ExpectAndReturn");
#define get_and_clear_Reset_Status_ExpectAndReturn(sensor, cmock_retval) get_and_clear_Reset_Status_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_and_clear_Reset_Status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, bool cmock_to_return);
typedef bool (* CMOCK_get_and_clear_Reset_Status_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_and_clear_Reset_Status_AddCallback(CMOCK_get_and_clear_Reset_Status_CALLBACK Callback);
void get_and_clear_Reset_Status_Stub(CMOCK_get_and_clear_Reset_Status_CALLBACK Callback);
#define get_and_clear_Reset_Status_StubWithCallback get_and_clear_Reset_Status_Stub
int get_and_clear_Reset_Status_CallCount(void);
#define enable_Accelerometer_Ignore() TEST_FAIL_MESSAGE("enable_Accelerometer requires _IgnoreAndReturn");
#define enable_Accelerometer_IgnoreAndReturn(cmock_retval) enable_Accelerometer_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_Accelerometer_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_Accelerometer_StopIgnore() enable_Accelerometer_CMockStopIgnore()
void enable_Accelerometer_CMockStopIgnore(void);
#define enable_Accelerometer_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_Accelerometer requires _ExpectAndReturn");
#define enable_Accelerometer_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_Accelerometer_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_Accelerometer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_Accelerometer_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_Accelerometer_AddCallback(CMOCK_enable_Accelerometer_CALLBACK Callback);
void enable_Accelerometer_Stub(CMOCK_enable_Accelerometer_CALLBACK Callback);
#define enable_Accelerometer_StubWithCallback enable_Accelerometer_Stub
int enable_Accelerometer_CallCount(void);
#define enable_LinearAcceleration_Ignore() TEST_FAIL_MESSAGE("enable_LinearAcceleration requires _IgnoreAndReturn");
#define enable_LinearAcceleration_IgnoreAndReturn(cmock_retval) enable_LinearAcceleration_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_LinearAcceleration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_LinearAcceleration_StopIgnore() enable_LinearAcceleration_CMockStopIgnore()
void enable_LinearAcceleration_CMockStopIgnore(void);
#define enable_LinearAcceleration_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_LinearAcceleration requires _ExpectAndReturn");
#define enable_LinearAcceleration_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_LinearAcceleration_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_LinearAcceleration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_LinearAcceleration_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_LinearAcceleration_AddCallback(CMOCK_enable_LinearAcceleration_CALLBACK Callback);
void enable_LinearAcceleration_Stub(CMOCK_enable_LinearAcceleration_CALLBACK Callback);
#define enable_LinearAcceleration_StubWithCallback enable_LinearAcceleration_Stub
int enable_LinearAcceleration_CallCount(void);
#define enable_Gravity_Ignore() TEST_FAIL_MESSAGE("enable_Gravity requires _IgnoreAndReturn");
#define enable_Gravity_IgnoreAndReturn(cmock_retval) enable_Gravity_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_Gravity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_Gravity_StopIgnore() enable_Gravity_CMockStopIgnore()
void enable_Gravity_CMockStopIgnore(void);
#define enable_Gravity_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_Gravity requires _ExpectAndReturn");
#define enable_Gravity_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_Gravity_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_Gravity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_Gravity_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_Gravity_AddCallback(CMOCK_enable_Gravity_CALLBACK Callback);
void enable_Gravity_Stub(CMOCK_enable_Gravity_CALLBACK Callback);
#define enable_Gravity_StubWithCallback enable_Gravity_Stub
int enable_Gravity_CallCount(void);
#define enable_RotationVector_Ignore() TEST_FAIL_MESSAGE("enable_RotationVector requires _IgnoreAndReturn");
#define enable_RotationVector_IgnoreAndReturn(cmock_retval) enable_RotationVector_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_RotationVector_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_RotationVector_StopIgnore() enable_RotationVector_CMockStopIgnore()
void enable_RotationVector_CMockStopIgnore(void);
#define enable_RotationVector_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_RotationVector requires _ExpectAndReturn");
#define enable_RotationVector_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_RotationVector_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_RotationVector_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_RotationVector_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_RotationVector_AddCallback(CMOCK_enable_RotationVector_CALLBACK Callback);
void enable_RotationVector_Stub(CMOCK_enable_RotationVector_CALLBACK Callback);
#define enable_RotationVector_StubWithCallback enable_RotationVector_Stub
int enable_RotationVector_CallCount(void);
#define enable_ARVR_stabilized_RotationVector_Ignore() TEST_FAIL_MESSAGE("enable_ARVR_stabilized_RotationVector requires _IgnoreAndReturn");
#define enable_ARVR_stabilized_RotationVector_IgnoreAndReturn(cmock_retval) enable_ARVR_stabilized_RotationVector_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_ARVR_stabilized_RotationVector_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_ARVR_stabilized_RotationVector_StopIgnore() enable_ARVR_stabilized_RotationVector_CMockStopIgnore()
void enable_ARVR_stabilized_RotationVector_CMockStopIgnore(void);
#define enable_ARVR_stabilized_RotationVector_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_ARVR_stabilized_RotationVector requires _ExpectAndReturn");
#define enable_ARVR_stabilized_RotationVector_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_ARVR_stabilized_RotationVector_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_ARVR_stabilized_RotationVector_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_ARVR_stabilized_RotationVector_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_ARVR_stabilized_RotationVector_AddCallback(CMOCK_enable_ARVR_stabilized_RotationVector_CALLBACK Callback);
void enable_ARVR_stabilized_RotationVector_Stub(CMOCK_enable_ARVR_stabilized_RotationVector_CALLBACK Callback);
#define enable_ARVR_stabilized_RotationVector_StubWithCallback enable_ARVR_stabilized_RotationVector_Stub
int enable_ARVR_stabilized_RotationVector_CallCount(void);
#define enable_GameRotationVector_Ignore() TEST_FAIL_MESSAGE("enable_GameRotationVector requires _IgnoreAndReturn");
#define enable_GameRotationVector_IgnoreAndReturn(cmock_retval) enable_GameRotationVector_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_GameRotationVector_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_GameRotationVector_StopIgnore() enable_GameRotationVector_CMockStopIgnore()
void enable_GameRotationVector_CMockStopIgnore(void);
#define enable_GameRotationVector_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_GameRotationVector requires _ExpectAndReturn");
#define enable_GameRotationVector_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_GameRotationVector_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_GameRotationVector_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_GameRotationVector_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_GameRotationVector_AddCallback(CMOCK_enable_GameRotationVector_CALLBACK Callback);
void enable_GameRotationVector_Stub(CMOCK_enable_GameRotationVector_CALLBACK Callback);
#define enable_GameRotationVector_StubWithCallback enable_GameRotationVector_Stub
int enable_GameRotationVector_CallCount(void);
#define enable_ARVR_stabilized_GameRotationVector_Ignore() TEST_FAIL_MESSAGE("enable_ARVR_stabilized_GameRotationVector requires _IgnoreAndReturn");
#define enable_ARVR_stabilized_GameRotationVector_IgnoreAndReturn(cmock_retval) enable_ARVR_stabilized_GameRotationVector_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_ARVR_stabilized_GameRotationVector_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_ARVR_stabilized_GameRotationVector_StopIgnore() enable_ARVR_stabilized_GameRotationVector_CMockStopIgnore()
void enable_ARVR_stabilized_GameRotationVector_CMockStopIgnore(void);
#define enable_ARVR_stabilized_GameRotationVector_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_ARVR_stabilized_GameRotationVector requires _ExpectAndReturn");
#define enable_ARVR_stabilized_GameRotationVector_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_ARVR_stabilized_GameRotationVector_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_ARVR_stabilized_GameRotationVector_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_ARVR_stabilized_GameRotationVector_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_ARVR_stabilized_GameRotationVector_AddCallback(CMOCK_enable_ARVR_stabilized_GameRotationVector_CALLBACK Callback);
void enable_ARVR_stabilized_GameRotationVector_Stub(CMOCK_enable_ARVR_stabilized_GameRotationVector_CALLBACK Callback);
#define enable_ARVR_stabilized_GameRotationVector_StubWithCallback enable_ARVR_stabilized_GameRotationVector_Stub
int enable_ARVR_stabilized_GameRotationVector_CallCount(void);
#define enable_StabilityClassifier_Ignore() TEST_FAIL_MESSAGE("enable_StabilityClassifier requires _IgnoreAndReturn");
#define enable_StabilityClassifier_IgnoreAndReturn(cmock_retval) enable_StabilityClassifier_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_StabilityClassifier_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_StabilityClassifier_StopIgnore() enable_StabilityClassifier_CMockStopIgnore()
void enable_StabilityClassifier_CMockStopIgnore(void);
#define enable_StabilityClassifier_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_StabilityClassifier requires _ExpectAndReturn");
#define enable_StabilityClassifier_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_StabilityClassifier_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_StabilityClassifier_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_StabilityClassifier_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_StabilityClassifier_AddCallback(CMOCK_enable_StabilityClassifier_CALLBACK Callback);
void enable_StabilityClassifier_Stub(CMOCK_enable_StabilityClassifier_CALLBACK Callback);
#define enable_StabilityClassifier_StubWithCallback enable_StabilityClassifier_Stub
int enable_StabilityClassifier_CallCount(void);
#define enable_TapDetector_Ignore() TEST_FAIL_MESSAGE("enable_TapDetector requires _IgnoreAndReturn");
#define enable_TapDetector_IgnoreAndReturn(cmock_retval) enable_TapDetector_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void enable_TapDetector_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define enable_TapDetector_StopIgnore() enable_TapDetector_CMockStopIgnore()
void enable_TapDetector_CMockStopIgnore(void);
#define enable_TapDetector_Expect(sensor, time_between_reports) TEST_FAIL_MESSAGE("enable_TapDetector requires _ExpectAndReturn");
#define enable_TapDetector_ExpectAndReturn(sensor, time_between_reports, cmock_retval) enable_TapDetector_CMockExpectAndReturn(__LINE__, sensor, time_between_reports, cmock_retval)
void enable_TapDetector_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t time_between_reports, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_enable_TapDetector_CALLBACK)(sensor_meta* sensor, uint16_t time_between_reports, int cmock_num_calls);
void enable_TapDetector_AddCallback(CMOCK_enable_TapDetector_CALLBACK Callback);
void enable_TapDetector_Stub(CMOCK_enable_TapDetector_CALLBACK Callback);
#define enable_TapDetector_StubWithCallback enable_TapDetector_Stub
int enable_TapDetector_CallCount(void);
#define data_available_Ignore() TEST_FAIL_MESSAGE("data_available requires _IgnoreAndReturn");
#define data_available_IgnoreAndReturn(cmock_retval) data_available_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void data_available_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define data_available_StopIgnore() data_available_CMockStopIgnore()
void data_available_CMockStopIgnore(void);
#define data_available_Expect(sensor) TEST_FAIL_MESSAGE("data_available requires _ExpectAndReturn");
#define data_available_ExpectAndReturn(sensor, cmock_retval) data_available_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void data_available_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, bool cmock_to_return);
typedef bool (* CMOCK_data_available_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void data_available_AddCallback(CMOCK_data_available_CALLBACK Callback);
void data_available_Stub(CMOCK_data_available_CALLBACK Callback);
#define data_available_StubWithCallback data_available_Stub
int data_available_CallCount(void);
#define get_Accelerometer_X_Ignore() TEST_FAIL_MESSAGE("get_Accelerometer_X requires _IgnoreAndReturn");
#define get_Accelerometer_X_IgnoreAndReturn(cmock_retval) get_Accelerometer_X_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Accelerometer_X_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Accelerometer_X_StopIgnore() get_Accelerometer_X_CMockStopIgnore()
void get_Accelerometer_X_CMockStopIgnore(void);
#define get_Accelerometer_X_Expect(sensor) TEST_FAIL_MESSAGE("get_Accelerometer_X requires _ExpectAndReturn");
#define get_Accelerometer_X_ExpectAndReturn(sensor, cmock_retval) get_Accelerometer_X_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Accelerometer_X_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Accelerometer_X_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Accelerometer_X_AddCallback(CMOCK_get_Accelerometer_X_CALLBACK Callback);
void get_Accelerometer_X_Stub(CMOCK_get_Accelerometer_X_CALLBACK Callback);
#define get_Accelerometer_X_StubWithCallback get_Accelerometer_X_Stub
int get_Accelerometer_X_CallCount(void);
#define get_Accelerometer_Y_Ignore() TEST_FAIL_MESSAGE("get_Accelerometer_Y requires _IgnoreAndReturn");
#define get_Accelerometer_Y_IgnoreAndReturn(cmock_retval) get_Accelerometer_Y_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Accelerometer_Y_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Accelerometer_Y_StopIgnore() get_Accelerometer_Y_CMockStopIgnore()
void get_Accelerometer_Y_CMockStopIgnore(void);
#define get_Accelerometer_Y_Expect(sensor) TEST_FAIL_MESSAGE("get_Accelerometer_Y requires _ExpectAndReturn");
#define get_Accelerometer_Y_ExpectAndReturn(sensor, cmock_retval) get_Accelerometer_Y_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Accelerometer_Y_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Accelerometer_Y_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Accelerometer_Y_AddCallback(CMOCK_get_Accelerometer_Y_CALLBACK Callback);
void get_Accelerometer_Y_Stub(CMOCK_get_Accelerometer_Y_CALLBACK Callback);
#define get_Accelerometer_Y_StubWithCallback get_Accelerometer_Y_Stub
int get_Accelerometer_Y_CallCount(void);
#define get_Accelerometer_Z_Ignore() TEST_FAIL_MESSAGE("get_Accelerometer_Z requires _IgnoreAndReturn");
#define get_Accelerometer_Z_IgnoreAndReturn(cmock_retval) get_Accelerometer_Z_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Accelerometer_Z_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Accelerometer_Z_StopIgnore() get_Accelerometer_Z_CMockStopIgnore()
void get_Accelerometer_Z_CMockStopIgnore(void);
#define get_Accelerometer_Z_Expect(sensor) TEST_FAIL_MESSAGE("get_Accelerometer_Z requires _ExpectAndReturn");
#define get_Accelerometer_Z_ExpectAndReturn(sensor, cmock_retval) get_Accelerometer_Z_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Accelerometer_Z_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Accelerometer_Z_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Accelerometer_Z_AddCallback(CMOCK_get_Accelerometer_Z_CALLBACK Callback);
void get_Accelerometer_Z_Stub(CMOCK_get_Accelerometer_Z_CALLBACK Callback);
#define get_Accelerometer_Z_StubWithCallback get_Accelerometer_Z_Stub
int get_Accelerometer_Z_CallCount(void);
#define get_Accelerometer_Accuracy_Ignore() TEST_FAIL_MESSAGE("get_Accelerometer_Accuracy requires _IgnoreAndReturn");
#define get_Accelerometer_Accuracy_IgnoreAndReturn(cmock_retval) get_Accelerometer_Accuracy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Accelerometer_Accuracy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_Accelerometer_Accuracy_StopIgnore() get_Accelerometer_Accuracy_CMockStopIgnore()
void get_Accelerometer_Accuracy_CMockStopIgnore(void);
#define get_Accelerometer_Accuracy_Expect(sensor) TEST_FAIL_MESSAGE("get_Accelerometer_Accuracy requires _ExpectAndReturn");
#define get_Accelerometer_Accuracy_ExpectAndReturn(sensor, cmock_retval) get_Accelerometer_Accuracy_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Accelerometer_Accuracy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_Accelerometer_Accuracy_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Accelerometer_Accuracy_AddCallback(CMOCK_get_Accelerometer_Accuracy_CALLBACK Callback);
void get_Accelerometer_Accuracy_Stub(CMOCK_get_Accelerometer_Accuracy_CALLBACK Callback);
#define get_Accelerometer_Accuracy_StubWithCallback get_Accelerometer_Accuracy_Stub
int get_Accelerometer_Accuracy_CallCount(void);
#define get_LinearAcceleration_X_Ignore() TEST_FAIL_MESSAGE("get_LinearAcceleration_X requires _IgnoreAndReturn");
#define get_LinearAcceleration_X_IgnoreAndReturn(cmock_retval) get_LinearAcceleration_X_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_LinearAcceleration_X_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_LinearAcceleration_X_StopIgnore() get_LinearAcceleration_X_CMockStopIgnore()
void get_LinearAcceleration_X_CMockStopIgnore(void);
#define get_LinearAcceleration_X_Expect(sensor) TEST_FAIL_MESSAGE("get_LinearAcceleration_X requires _ExpectAndReturn");
#define get_LinearAcceleration_X_ExpectAndReturn(sensor, cmock_retval) get_LinearAcceleration_X_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_LinearAcceleration_X_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_LinearAcceleration_X_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_LinearAcceleration_X_AddCallback(CMOCK_get_LinearAcceleration_X_CALLBACK Callback);
void get_LinearAcceleration_X_Stub(CMOCK_get_LinearAcceleration_X_CALLBACK Callback);
#define get_LinearAcceleration_X_StubWithCallback get_LinearAcceleration_X_Stub
int get_LinearAcceleration_X_CallCount(void);
#define get_LinearAcceleration_Y_Ignore() TEST_FAIL_MESSAGE("get_LinearAcceleration_Y requires _IgnoreAndReturn");
#define get_LinearAcceleration_Y_IgnoreAndReturn(cmock_retval) get_LinearAcceleration_Y_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_LinearAcceleration_Y_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_LinearAcceleration_Y_StopIgnore() get_LinearAcceleration_Y_CMockStopIgnore()
void get_LinearAcceleration_Y_CMockStopIgnore(void);
#define get_LinearAcceleration_Y_Expect(sensor) TEST_FAIL_MESSAGE("get_LinearAcceleration_Y requires _ExpectAndReturn");
#define get_LinearAcceleration_Y_ExpectAndReturn(sensor, cmock_retval) get_LinearAcceleration_Y_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_LinearAcceleration_Y_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_LinearAcceleration_Y_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_LinearAcceleration_Y_AddCallback(CMOCK_get_LinearAcceleration_Y_CALLBACK Callback);
void get_LinearAcceleration_Y_Stub(CMOCK_get_LinearAcceleration_Y_CALLBACK Callback);
#define get_LinearAcceleration_Y_StubWithCallback get_LinearAcceleration_Y_Stub
int get_LinearAcceleration_Y_CallCount(void);
#define get_LinearAcceleration_Z_Ignore() TEST_FAIL_MESSAGE("get_LinearAcceleration_Z requires _IgnoreAndReturn");
#define get_LinearAcceleration_Z_IgnoreAndReturn(cmock_retval) get_LinearAcceleration_Z_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_LinearAcceleration_Z_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_LinearAcceleration_Z_StopIgnore() get_LinearAcceleration_Z_CMockStopIgnore()
void get_LinearAcceleration_Z_CMockStopIgnore(void);
#define get_LinearAcceleration_Z_Expect(sensor) TEST_FAIL_MESSAGE("get_LinearAcceleration_Z requires _ExpectAndReturn");
#define get_LinearAcceleration_Z_ExpectAndReturn(sensor, cmock_retval) get_LinearAcceleration_Z_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_LinearAcceleration_Z_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_LinearAcceleration_Z_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_LinearAcceleration_Z_AddCallback(CMOCK_get_LinearAcceleration_Z_CALLBACK Callback);
void get_LinearAcceleration_Z_Stub(CMOCK_get_LinearAcceleration_Z_CALLBACK Callback);
#define get_LinearAcceleration_Z_StubWithCallback get_LinearAcceleration_Z_Stub
int get_LinearAcceleration_Z_CallCount(void);
#define get_LinearAcceleration_Accuracy_Ignore() TEST_FAIL_MESSAGE("get_LinearAcceleration_Accuracy requires _IgnoreAndReturn");
#define get_LinearAcceleration_Accuracy_IgnoreAndReturn(cmock_retval) get_LinearAcceleration_Accuracy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_LinearAcceleration_Accuracy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_LinearAcceleration_Accuracy_StopIgnore() get_LinearAcceleration_Accuracy_CMockStopIgnore()
void get_LinearAcceleration_Accuracy_CMockStopIgnore(void);
#define get_LinearAcceleration_Accuracy_Expect(sensor) TEST_FAIL_MESSAGE("get_LinearAcceleration_Accuracy requires _ExpectAndReturn");
#define get_LinearAcceleration_Accuracy_ExpectAndReturn(sensor, cmock_retval) get_LinearAcceleration_Accuracy_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_LinearAcceleration_Accuracy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_LinearAcceleration_Accuracy_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_LinearAcceleration_Accuracy_AddCallback(CMOCK_get_LinearAcceleration_Accuracy_CALLBACK Callback);
void get_LinearAcceleration_Accuracy_Stub(CMOCK_get_LinearAcceleration_Accuracy_CALLBACK Callback);
#define get_LinearAcceleration_Accuracy_StubWithCallback get_LinearAcceleration_Accuracy_Stub
int get_LinearAcceleration_Accuracy_CallCount(void);
#define get_Gravity_X_Ignore() TEST_FAIL_MESSAGE("get_Gravity_X requires _IgnoreAndReturn");
#define get_Gravity_X_IgnoreAndReturn(cmock_retval) get_Gravity_X_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Gravity_X_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Gravity_X_StopIgnore() get_Gravity_X_CMockStopIgnore()
void get_Gravity_X_CMockStopIgnore(void);
#define get_Gravity_X_Expect(sensor) TEST_FAIL_MESSAGE("get_Gravity_X requires _ExpectAndReturn");
#define get_Gravity_X_ExpectAndReturn(sensor, cmock_retval) get_Gravity_X_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Gravity_X_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Gravity_X_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Gravity_X_AddCallback(CMOCK_get_Gravity_X_CALLBACK Callback);
void get_Gravity_X_Stub(CMOCK_get_Gravity_X_CALLBACK Callback);
#define get_Gravity_X_StubWithCallback get_Gravity_X_Stub
int get_Gravity_X_CallCount(void);
#define get_Gravity_Y_Ignore() TEST_FAIL_MESSAGE("get_Gravity_Y requires _IgnoreAndReturn");
#define get_Gravity_Y_IgnoreAndReturn(cmock_retval) get_Gravity_Y_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Gravity_Y_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Gravity_Y_StopIgnore() get_Gravity_Y_CMockStopIgnore()
void get_Gravity_Y_CMockStopIgnore(void);
#define get_Gravity_Y_Expect(sensor) TEST_FAIL_MESSAGE("get_Gravity_Y requires _ExpectAndReturn");
#define get_Gravity_Y_ExpectAndReturn(sensor, cmock_retval) get_Gravity_Y_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Gravity_Y_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Gravity_Y_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Gravity_Y_AddCallback(CMOCK_get_Gravity_Y_CALLBACK Callback);
void get_Gravity_Y_Stub(CMOCK_get_Gravity_Y_CALLBACK Callback);
#define get_Gravity_Y_StubWithCallback get_Gravity_Y_Stub
int get_Gravity_Y_CallCount(void);
#define get_Gravity_Z_Ignore() TEST_FAIL_MESSAGE("get_Gravity_Z requires _IgnoreAndReturn");
#define get_Gravity_Z_IgnoreAndReturn(cmock_retval) get_Gravity_Z_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Gravity_Z_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Gravity_Z_StopIgnore() get_Gravity_Z_CMockStopIgnore()
void get_Gravity_Z_CMockStopIgnore(void);
#define get_Gravity_Z_Expect(sensor) TEST_FAIL_MESSAGE("get_Gravity_Z requires _ExpectAndReturn");
#define get_Gravity_Z_ExpectAndReturn(sensor, cmock_retval) get_Gravity_Z_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Gravity_Z_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Gravity_Z_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Gravity_Z_AddCallback(CMOCK_get_Gravity_Z_CALLBACK Callback);
void get_Gravity_Z_Stub(CMOCK_get_Gravity_Z_CALLBACK Callback);
#define get_Gravity_Z_StubWithCallback get_Gravity_Z_Stub
int get_Gravity_Z_CallCount(void);
#define get_Gravity_Accuracy_Ignore() TEST_FAIL_MESSAGE("get_Gravity_Accuracy requires _IgnoreAndReturn");
#define get_Gravity_Accuracy_IgnoreAndReturn(cmock_retval) get_Gravity_Accuracy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Gravity_Accuracy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_Gravity_Accuracy_StopIgnore() get_Gravity_Accuracy_CMockStopIgnore()
void get_Gravity_Accuracy_CMockStopIgnore(void);
#define get_Gravity_Accuracy_Expect(sensor) TEST_FAIL_MESSAGE("get_Gravity_Accuracy requires _ExpectAndReturn");
#define get_Gravity_Accuracy_ExpectAndReturn(sensor, cmock_retval) get_Gravity_Accuracy_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Gravity_Accuracy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_Gravity_Accuracy_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Gravity_Accuracy_AddCallback(CMOCK_get_Gravity_Accuracy_CALLBACK Callback);
void get_Gravity_Accuracy_Stub(CMOCK_get_Gravity_Accuracy_CALLBACK Callback);
#define get_Gravity_Accuracy_StubWithCallback get_Gravity_Accuracy_Stub
int get_Gravity_Accuracy_CallCount(void);
#define get_Quat_I_Ignore() TEST_FAIL_MESSAGE("get_Quat_I requires _IgnoreAndReturn");
#define get_Quat_I_IgnoreAndReturn(cmock_retval) get_Quat_I_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_I_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Quat_I_StopIgnore() get_Quat_I_CMockStopIgnore()
void get_Quat_I_CMockStopIgnore(void);
#define get_Quat_I_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_I requires _ExpectAndReturn");
#define get_Quat_I_ExpectAndReturn(sensor, cmock_retval) get_Quat_I_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_I_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Quat_I_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_I_AddCallback(CMOCK_get_Quat_I_CALLBACK Callback);
void get_Quat_I_Stub(CMOCK_get_Quat_I_CALLBACK Callback);
#define get_Quat_I_StubWithCallback get_Quat_I_Stub
int get_Quat_I_CallCount(void);
#define get_Quat_J_Ignore() TEST_FAIL_MESSAGE("get_Quat_J requires _IgnoreAndReturn");
#define get_Quat_J_IgnoreAndReturn(cmock_retval) get_Quat_J_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_J_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Quat_J_StopIgnore() get_Quat_J_CMockStopIgnore()
void get_Quat_J_CMockStopIgnore(void);
#define get_Quat_J_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_J requires _ExpectAndReturn");
#define get_Quat_J_ExpectAndReturn(sensor, cmock_retval) get_Quat_J_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_J_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Quat_J_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_J_AddCallback(CMOCK_get_Quat_J_CALLBACK Callback);
void get_Quat_J_Stub(CMOCK_get_Quat_J_CALLBACK Callback);
#define get_Quat_J_StubWithCallback get_Quat_J_Stub
int get_Quat_J_CallCount(void);
#define get_Quat_K_Ignore() TEST_FAIL_MESSAGE("get_Quat_K requires _IgnoreAndReturn");
#define get_Quat_K_IgnoreAndReturn(cmock_retval) get_Quat_K_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_K_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Quat_K_StopIgnore() get_Quat_K_CMockStopIgnore()
void get_Quat_K_CMockStopIgnore(void);
#define get_Quat_K_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_K requires _ExpectAndReturn");
#define get_Quat_K_ExpectAndReturn(sensor, cmock_retval) get_Quat_K_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_K_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Quat_K_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_K_AddCallback(CMOCK_get_Quat_K_CALLBACK Callback);
void get_Quat_K_Stub(CMOCK_get_Quat_K_CALLBACK Callback);
#define get_Quat_K_StubWithCallback get_Quat_K_Stub
int get_Quat_K_CallCount(void);
#define get_Quat_Real_Ignore() TEST_FAIL_MESSAGE("get_Quat_Real requires _IgnoreAndReturn");
#define get_Quat_Real_IgnoreAndReturn(cmock_retval) get_Quat_Real_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_Real_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Quat_Real_StopIgnore() get_Quat_Real_CMockStopIgnore()
void get_Quat_Real_CMockStopIgnore(void);
#define get_Quat_Real_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_Real requires _ExpectAndReturn");
#define get_Quat_Real_ExpectAndReturn(sensor, cmock_retval) get_Quat_Real_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_Real_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Quat_Real_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_Real_AddCallback(CMOCK_get_Quat_Real_CALLBACK Callback);
void get_Quat_Real_Stub(CMOCK_get_Quat_Real_CALLBACK Callback);
#define get_Quat_Real_StubWithCallback get_Quat_Real_Stub
int get_Quat_Real_CallCount(void);
#define get_Quat_Radian_Accuracy_Ignore() TEST_FAIL_MESSAGE("get_Quat_Radian_Accuracy requires _IgnoreAndReturn");
#define get_Quat_Radian_Accuracy_IgnoreAndReturn(cmock_retval) get_Quat_Radian_Accuracy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_Radian_Accuracy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define get_Quat_Radian_Accuracy_StopIgnore() get_Quat_Radian_Accuracy_CMockStopIgnore()
void get_Quat_Radian_Accuracy_CMockStopIgnore(void);
#define get_Quat_Radian_Accuracy_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_Radian_Accuracy requires _ExpectAndReturn");
#define get_Quat_Radian_Accuracy_ExpectAndReturn(sensor, cmock_retval) get_Quat_Radian_Accuracy_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_Radian_Accuracy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, float cmock_to_return);
typedef float (* CMOCK_get_Quat_Radian_Accuracy_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_Radian_Accuracy_AddCallback(CMOCK_get_Quat_Radian_Accuracy_CALLBACK Callback);
void get_Quat_Radian_Accuracy_Stub(CMOCK_get_Quat_Radian_Accuracy_CALLBACK Callback);
#define get_Quat_Radian_Accuracy_StubWithCallback get_Quat_Radian_Accuracy_Stub
int get_Quat_Radian_Accuracy_CallCount(void);
#define get_Quat_Accuracy_Ignore() TEST_FAIL_MESSAGE("get_Quat_Accuracy requires _IgnoreAndReturn");
#define get_Quat_Accuracy_IgnoreAndReturn(cmock_retval) get_Quat_Accuracy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Quat_Accuracy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_Quat_Accuracy_StopIgnore() get_Quat_Accuracy_CMockStopIgnore()
void get_Quat_Accuracy_CMockStopIgnore(void);
#define get_Quat_Accuracy_Expect(sensor) TEST_FAIL_MESSAGE("get_Quat_Accuracy requires _ExpectAndReturn");
#define get_Quat_Accuracy_ExpectAndReturn(sensor, cmock_retval) get_Quat_Accuracy_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_Quat_Accuracy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_Quat_Accuracy_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_Quat_Accuracy_AddCallback(CMOCK_get_Quat_Accuracy_CALLBACK Callback);
void get_Quat_Accuracy_Stub(CMOCK_get_Quat_Accuracy_CALLBACK Callback);
#define get_Quat_Accuracy_StubWithCallback get_Quat_Accuracy_Stub
int get_Quat_Accuracy_CallCount(void);
#define get_StabilityClassifier_Ignore() TEST_FAIL_MESSAGE("get_StabilityClassifier requires _IgnoreAndReturn");
#define get_StabilityClassifier_IgnoreAndReturn(cmock_retval) get_StabilityClassifier_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_StabilityClassifier_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_StabilityClassifier_StopIgnore() get_StabilityClassifier_CMockStopIgnore()
void get_StabilityClassifier_CMockStopIgnore(void);
#define get_StabilityClassifier_Expect(sensor) TEST_FAIL_MESSAGE("get_StabilityClassifier requires _ExpectAndReturn");
#define get_StabilityClassifier_ExpectAndReturn(sensor, cmock_retval) get_StabilityClassifier_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_StabilityClassifier_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_StabilityClassifier_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_StabilityClassifier_AddCallback(CMOCK_get_StabilityClassifier_CALLBACK Callback);
void get_StabilityClassifier_Stub(CMOCK_get_StabilityClassifier_CALLBACK Callback);
#define get_StabilityClassifier_StubWithCallback get_StabilityClassifier_Stub
int get_StabilityClassifier_CallCount(void);
#define update_TapDetector_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("update_TapDetector requires _Ignore (not AndReturn)");
#define update_TapDetector_Ignore() update_TapDetector_CMockIgnore()
void update_TapDetector_CMockIgnore(void);
#define update_TapDetector_StopIgnore() update_TapDetector_CMockStopIgnore()
void update_TapDetector_CMockStopIgnore(void);
#define update_TapDetector_ExpectAndReturn(sensor, cmock_retval) TEST_FAIL_MESSAGE("update_TapDetector requires _Expect (not AndReturn)");
#define update_TapDetector_Expect(sensor) update_TapDetector_CMockExpect(__LINE__, sensor)
void update_TapDetector_CMockExpect(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor);
typedef void (* CMOCK_update_TapDetector_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void update_TapDetector_AddCallback(CMOCK_update_TapDetector_CALLBACK Callback);
void update_TapDetector_Stub(CMOCK_update_TapDetector_CALLBACK Callback);
#define update_TapDetector_StubWithCallback update_TapDetector_Stub
int update_TapDetector_CallCount(void);
#define get_ProductID_Ignore() TEST_FAIL_MESSAGE("get_ProductID requires _IgnoreAndReturn");
#define get_ProductID_IgnoreAndReturn(cmock_retval) get_ProductID_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_ProductID_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_ProductID_StopIgnore() get_ProductID_CMockStopIgnore()
void get_ProductID_CMockStopIgnore(void);
#define get_ProductID_Expect(sensor) TEST_FAIL_MESSAGE("get_ProductID requires _ExpectAndReturn");
#define get_ProductID_ExpectAndReturn(sensor, cmock_retval) get_ProductID_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_ProductID_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_ProductID_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_ProductID_AddCallback(CMOCK_get_ProductID_CALLBACK Callback);
void get_ProductID_Stub(CMOCK_get_ProductID_CALLBACK Callback);
#define get_ProductID_StubWithCallback get_ProductID_Stub
int get_ProductID_CallCount(void);
#define get_Reset_Reason_String_Ignore() TEST_FAIL_MESSAGE("get_Reset_Reason_String requires _IgnoreAndReturn");
#define get_Reset_Reason_String_IgnoreAndReturn(cmock_retval) get_Reset_Reason_String_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_Reset_Reason_String_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const char* cmock_to_return);
#define get_Reset_Reason_String_StopIgnore() get_Reset_Reason_String_CMockStopIgnore()
void get_Reset_Reason_String_CMockStopIgnore(void);
#define get_Reset_Reason_String_Expect(reset_reason) TEST_FAIL_MESSAGE("get_Reset_Reason_String requires _ExpectAndReturn");
#define get_Reset_Reason_String_ExpectAndReturn(reset_reason, cmock_retval) get_Reset_Reason_String_CMockExpectAndReturn(__LINE__, reset_reason, cmock_retval)
void get_Reset_Reason_String_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t reset_reason, const char* cmock_to_return);
typedef const char* (* CMOCK_get_Reset_Reason_String_CALLBACK)(uint8_t reset_reason, int cmock_num_calls);
void get_Reset_Reason_String_AddCallback(CMOCK_get_Reset_Reason_String_CALLBACK Callback);
void get_Reset_Reason_String_Stub(CMOCK_get_Reset_Reason_String_CALLBACK Callback);
#define get_Reset_Reason_String_StubWithCallback get_Reset_Reason_String_Stub
int get_Reset_Reason_String_CallCount(void);
#define check_Connection_IMU_Ignore() TEST_FAIL_MESSAGE("check_Connection_IMU requires _IgnoreAndReturn");
#define check_Connection_IMU_IgnoreAndReturn(cmock_retval) check_Connection_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void check_Connection_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define check_Connection_IMU_StopIgnore() check_Connection_IMU_CMockStopIgnore()
void check_Connection_IMU_CMockStopIgnore(void);
#define check_Connection_IMU_Expect(sensor) TEST_FAIL_MESSAGE("check_Connection_IMU requires _ExpectAndReturn");
#define check_Connection_IMU_ExpectAndReturn(sensor, cmock_retval) check_Connection_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void check_Connection_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_check_Connection_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void check_Connection_IMU_AddCallback(CMOCK_check_Connection_IMU_CALLBACK Callback);
void check_Connection_IMU_Stub(CMOCK_check_Connection_IMU_CALLBACK Callback);
#define check_Connection_IMU_StubWithCallback check_Connection_IMU_Stub
int check_Connection_IMU_CallCount(void);
#define tare_IMU_Ignore() TEST_FAIL_MESSAGE("tare_IMU requires _IgnoreAndReturn");
#define tare_IMU_IgnoreAndReturn(cmock_retval) tare_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tare_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define tare_IMU_StopIgnore() tare_IMU_CMockStopIgnore()
void tare_IMU_CMockStopIgnore(void);
#define tare_IMU_Expect(sensor, all_Axis) TEST_FAIL_MESSAGE("tare_IMU requires _ExpectAndReturn");
#define tare_IMU_ExpectAndReturn(sensor, all_Axis, cmock_retval) tare_IMU_CMockExpectAndReturn(__LINE__, sensor, all_Axis, cmock_retval)
void tare_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, bool all_Axis, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_tare_IMU_CALLBACK)(sensor_meta* sensor, bool all_Axis, int cmock_num_calls);
void tare_IMU_AddCallback(CMOCK_tare_IMU_CALLBACK Callback);
void tare_IMU_Stub(CMOCK_tare_IMU_CALLBACK Callback);
#define tare_IMU_StubWithCallback tare_IMU_Stub
int tare_IMU_CallCount(void);
#define tare_persist_IMU_Ignore() TEST_FAIL_MESSAGE("tare_persist_IMU requires _IgnoreAndReturn");
#define tare_persist_IMU_IgnoreAndReturn(cmock_retval) tare_persist_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tare_persist_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define tare_persist_IMU_StopIgnore() tare_persist_IMU_CMockStopIgnore()
void tare_persist_IMU_CMockStopIgnore(void);
#define tare_persist_IMU_Expect(sensor) TEST_FAIL_MESSAGE("tare_persist_IMU requires _ExpectAndReturn");
#define tare_persist_IMU_ExpectAndReturn(sensor, cmock_retval) tare_persist_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void tare_persist_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_tare_persist_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void tare_persist_IMU_AddCallback(CMOCK_tare_persist_IMU_CALLBACK Callback);
void tare_persist_IMU_Stub(CMOCK_tare_persist_IMU_CALLBACK Callback);
#define tare_persist_IMU_StubWithCallback tare_persist_IMU_Stub
int tare_persist_IMU_CallCount(void);
#define tare_set_reorientation_IMU_Ignore() TEST_FAIL_MESSAGE("tare_set_reorientation_IMU requires _IgnoreAndReturn");
#define tare_set_reorientation_IMU_IgnoreAndReturn(cmock_retval) tare_set_reorientation_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tare_set_reorientation_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define tare_set_reorientation_IMU_StopIgnore() tare_set_reorientation_IMU_CMockStopIgnore()
void tare_set_reorientation_IMU_CMockStopIgnore(void);
#define tare_set_reorientation_IMU_Expect(sensor) TEST_FAIL_MESSAGE("tare_set_reorientation_IMU requires _ExpectAndReturn");
#define tare_set_reorientation_IMU_ExpectAndReturn(sensor, cmock_retval) tare_set_reorientation_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void tare_set_reorientation_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_tare_set_reorientation_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void tare_set_reorientation_IMU_AddCallback(CMOCK_tare_set_reorientation_IMU_CALLBACK Callback);
void tare_set_reorientation_IMU_Stub(CMOCK_tare_set_reorientation_IMU_CALLBACK Callback);
#define tare_set_reorientation_IMU_StubWithCallback tare_set_reorientation_IMU_Stub
int tare_set_reorientation_IMU_CallCount(void);
#define tare_clear_IMU_Ignore() TEST_FAIL_MESSAGE("tare_clear_IMU requires _IgnoreAndReturn");
#define tare_clear_IMU_IgnoreAndReturn(cmock_retval) tare_clear_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tare_clear_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define tare_clear_IMU_StopIgnore() tare_clear_IMU_CMockStopIgnore()
void tare_clear_IMU_CMockStopIgnore(void);
#define tare_clear_IMU_Expect(sensor) TEST_FAIL_MESSAGE("tare_clear_IMU requires _ExpectAndReturn");
#define tare_clear_IMU_ExpectAndReturn(sensor, cmock_retval) tare_clear_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void tare_clear_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_tare_clear_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void tare_clear_IMU_AddCallback(CMOCK_tare_clear_IMU_CALLBACK Callback);
void tare_clear_IMU_Stub(CMOCK_tare_clear_IMU_CALLBACK Callback);
#define tare_clear_IMU_StubWithCallback tare_clear_IMU_Stub
int tare_clear_IMU_CallCount(void);
#define reinitialize_IMU_Ignore() TEST_FAIL_MESSAGE("reinitialize_IMU requires _IgnoreAndReturn");
#define reinitialize_IMU_IgnoreAndReturn(cmock_retval) reinitialize_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void reinitialize_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define reinitialize_IMU_StopIgnore() reinitialize_IMU_CMockStopIgnore()
void reinitialize_IMU_CMockStopIgnore(void);
#define reinitialize_IMU_Expect(sensor) TEST_FAIL_MESSAGE("reinitialize_IMU requires _ExpectAndReturn");
#define reinitialize_IMU_ExpectAndReturn(sensor, cmock_retval) reinitialize_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void reinitialize_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_reinitialize_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void reinitialize_IMU_AddCallback(CMOCK_reinitialize_IMU_CALLBACK Callback);
void reinitialize_IMU_Stub(CMOCK_reinitialize_IMU_CALLBACK Callback);
#define reinitialize_IMU_StubWithCallback reinitialize_IMU_Stub
int reinitialize_IMU_CallCount(void);
#define save_DCD_IMU_Ignore() TEST_FAIL_MESSAGE("save_DCD_IMU requires _IgnoreAndReturn");
#define save_DCD_IMU_IgnoreAndReturn(cmock_retval) save_DCD_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void save_DCD_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define save_DCD_IMU_StopIgnore() save_DCD_IMU_CMockStopIgnore()
void save_DCD_IMU_CMockStopIgnore(void);
#define save_DCD_IMU_Expect(sensor) TEST_FAIL_MESSAGE("save_DCD_IMU requires _ExpectAndReturn");
#define save_DCD_IMU_ExpectAndReturn(sensor, cmock_retval) save_DCD_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void save_DCD_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_save_DCD_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void save_DCD_IMU_AddCallback(CMOCK_save_DCD_IMU_CALLBACK Callback);
void save_DCD_IMU_Stub(CMOCK_save_DCD_IMU_CALLBACK Callback);
#define save_DCD_IMU_StubWithCallback save_DCD_IMU_Stub
int save_DCD_IMU_CallCount(void);
#define configure_ME_Calibration_IMU_Ignore() TEST_FAIL_MESSAGE("configure_ME_Calibration_IMU requires _IgnoreAndReturn");
#define configure_ME_Calibration_IMU_IgnoreAndReturn(cmock_retval) configure_ME_Calibration_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void configure_ME_Calibration_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define configure_ME_Calibration_IMU_StopIgnore() configure_ME_Calibration_IMU_CMockStopIgnore()
void configure_ME_Calibration_IMU_CMockStopIgnore(void);
#define configure_ME_Calibration_IMU_Expect(sensor, enable_Accel_Cal, enable_Gyro_Cal, enable_Mag_Cal, enable_Planar_Accel_Cal, enable_On_Table_Cal) TEST_FAIL_MESSAGE("configure_ME_Calibration_IMU requires _ExpectAndReturn");
#define configure_ME_Calibration_IMU_ExpectAndReturn(sensor, enable_Accel_Cal, enable_Gyro_Cal, enable_Mag_Cal, enable_Planar_Accel_Cal, enable_On_Table_Cal, cmock_retval) configure_ME_Calibration_IMU_CMockExpectAndReturn(__LINE__, sensor, enable_Accel_Cal, enable_Gyro_Cal, enable_Mag_Cal, enable_Planar_Accel_Cal, enable_On_Table_Cal, cmock_retval)
void configure_ME_Calibration_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, bool enable_Accel_Cal, bool enable_Gyro_Cal, bool enable_Mag_Cal, bool enable_Planar_Accel_Cal, bool enable_On_Table_Cal, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_configure_ME_Calibration_IMU_CALLBACK)(sensor_meta* sensor, bool enable_Accel_Cal, bool enable_Gyro_Cal, bool enable_Mag_Cal, bool enable_Planar_Accel_Cal, bool enable_On_Table_Cal, int cmock_num_calls);
void configure_ME_Calibration_IMU_AddCallback(CMOCK_configure_ME_Calibration_IMU_CALLBACK Callback);
void configure_ME_Calibration_IMU_Stub(CMOCK_configure_ME_Calibration_IMU_CALLBACK Callback);
#define configure_ME_Calibration_IMU_StubWithCallback configure_ME_Calibration_IMU_Stub
int configure_ME_Calibration_IMU_CallCount(void);
#define get_ME_Calibration_Config_IMU_Ignore() TEST_FAIL_MESSAGE("get_ME_Calibration_Config_IMU requires _IgnoreAndReturn");
#define get_ME_Calibration_Config_IMU_IgnoreAndReturn(cmock_retval) get_ME_Calibration_Config_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_ME_Calibration_Config_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define get_ME_Calibration_Config_IMU_StopIgnore() get_ME_Calibration_Config_IMU_CMockStopIgnore()
void get_ME_Calibration_Config_IMU_CMockStopIgnore(void);
#define get_ME_Calibration_Config_IMU_Expect(sensor) TEST_FAIL_MESSAGE("get_ME_Calibration_Config_IMU requires _ExpectAndReturn");
#define get_ME_Calibration_Config_IMU_ExpectAndReturn(sensor, cmock_retval) get_ME_Calibration_Config_IMU_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void get_ME_Calibration_Config_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_get_ME_Calibration_Config_IMU_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void get_ME_Calibration_Config_IMU_AddCallback(CMOCK_get_ME_Calibration_Config_IMU_CALLBACK Callback);
void get_ME_Calibration_Config_IMU_Stub(CMOCK_get_ME_Calibration_Config_IMU_CALLBACK Callback);
#define get_ME_Calibration_Config_IMU_StubWithCallback get_ME_Calibration_Config_IMU_Stub
int get_ME_Calibration_Config_IMU_CallCount(void);
#define config_periodic_DCD_IMU_Ignore() TEST_FAIL_MESSAGE("config_periodic_DCD_IMU requires _IgnoreAndReturn");
#define config_periodic_DCD_IMU_IgnoreAndReturn(cmock_retval) config_periodic_DCD_IMU_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void config_periodic_DCD_IMU_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define config_periodic_DCD_IMU_StopIgnore() config_periodic_DCD_IMU_CMockStopIgnore()
void config_periodic_DCD_IMU_CMockStopIgnore(void);
#define config_periodic_DCD_IMU_Expect(sensor, enable_periodic_DCD) TEST_FAIL_MESSAGE("config_periodic_DCD_IMU requires _ExpectAndReturn");
#define config_periodic_DCD_IMU_ExpectAndReturn(sensor, enable_periodic_DCD, cmock_retval) config_periodic_DCD_IMU_CMockExpectAndReturn(__LINE__, sensor, enable_periodic_DCD, cmock_retval)
void config_periodic_DCD_IMU_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, bool enable_periodic_DCD, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_config_periodic_DCD_IMU_CALLBACK)(sensor_meta* sensor, bool enable_periodic_DCD, int cmock_num_calls);
void config_periodic_DCD_IMU_AddCallback(CMOCK_config_periodic_DCD_IMU_CALLBACK Callback);
void config_periodic_DCD_IMU_Stub(CMOCK_config_periodic_DCD_IMU_CALLBACK Callback);
#define config_periodic_DCD_IMU_StubWithCallback config_periodic_DCD_IMU_Stub
int config_periodic_DCD_IMU_CallCount(void);
#define check_Command_Success_Ignore() TEST_FAIL_MESSAGE("check_Command_Success requires _IgnoreAndReturn");
#define check_Command_Success_IgnoreAndReturn(cmock_retval) check_Command_Success_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void check_Command_Success_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define check_Command_Success_StopIgnore() check_Command_Success_CMockStopIgnore()
void check_Command_Success_CMockStopIgnore(void);
#define check_Command_Success_Expect(sensor, status_command) TEST_FAIL_MESSAGE("check_Command_Success requires _ExpectAndReturn");
#define check_Command_Success_ExpectAndReturn(sensor, status_command, cmock_retval) check_Command_Success_CMockExpectAndReturn(__LINE__, sensor, status_command, cmock_retval)
void check_Command_Success_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint8_t status_command, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_check_Command_Success_CALLBACK)(sensor_meta* sensor, uint8_t status_command, int cmock_num_calls);
void check_Command_Success_AddCallback(CMOCK_check_Command_Success_CALLBACK Callback);
void check_Command_Success_Stub(CMOCK_check_Command_Success_CALLBACK Callback);
#define check_Command_Success_StubWithCallback check_Command_Success_Stub
int check_Command_Success_CallCount(void);
#define deassert_csn_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deassert_csn requires _Ignore (not AndReturn)");
#define deassert_csn_Ignore() deassert_csn_CMockIgnore()
void deassert_csn_CMockIgnore(void);
#define deassert_csn_StopIgnore() deassert_csn_CMockStopIgnore()
void deassert_csn_CMockStopIgnore(void);
#define deassert_csn_ExpectAndReturn(sensor, cmock_retval) TEST_FAIL_MESSAGE("deassert_csn requires _Expect (not AndReturn)");
#define deassert_csn_Expect(sensor) deassert_csn_CMockExpect(__LINE__, sensor)
void deassert_csn_CMockExpect(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor);
typedef void (* CMOCK_deassert_csn_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void deassert_csn_AddCallback(CMOCK_deassert_csn_CALLBACK Callback);
void deassert_csn_Stub(CMOCK_deassert_csn_CALLBACK Callback);
#define deassert_csn_StubWithCallback deassert_csn_Stub
int deassert_csn_CallCount(void);
#define read_FRS_Ignore() TEST_FAIL_MESSAGE("read_FRS requires _IgnoreAndReturn");
#define read_FRS_IgnoreAndReturn(cmock_retval) read_FRS_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void read_FRS_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define read_FRS_StopIgnore() read_FRS_CMockStopIgnore()
void read_FRS_CMockStopIgnore(void);
#define read_FRS_Expect(sensor, frs_type, buffer, max_words, words_read) TEST_FAIL_MESSAGE("read_FRS requires _ExpectAndReturn");
#define read_FRS_ExpectAndReturn(sensor, frs_type, buffer, max_words, words_read, cmock_retval) read_FRS_CMockExpectAndReturn(__LINE__, sensor, frs_type, buffer, max_words, words_read, cmock_retval)
void read_FRS_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t frs_type, uint32_t* buffer, uint16_t max_words, uint16_t* words_read, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_read_FRS_CALLBACK)(sensor_meta* sensor, uint16_t frs_type, uint32_t* buffer, uint16_t max_words, uint16_t* words_read, int cmock_num_calls);
void read_FRS_AddCallback(CMOCK_read_FRS_CALLBACK Callback);
void read_FRS_Stub(CMOCK_read_FRS_CALLBACK Callback);
#define read_FRS_StubWithCallback read_FRS_Stub
int read_FRS_CallCount(void);
#define erase_FRS_Ignore() TEST_FAIL_MESSAGE("erase_FRS requires _IgnoreAndReturn");
#define erase_FRS_IgnoreAndReturn(cmock_retval) erase_FRS_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void erase_FRS_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define erase_FRS_StopIgnore() erase_FRS_CMockStopIgnore()
void erase_FRS_CMockStopIgnore(void);
#define erase_FRS_Expect(sensor, frs_type) TEST_FAIL_MESSAGE("erase_FRS requires _ExpectAndReturn");
#define erase_FRS_ExpectAndReturn(sensor, frs_type, cmock_retval) erase_FRS_CMockExpectAndReturn(__LINE__, sensor, frs_type, cmock_retval)
void erase_FRS_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t frs_type, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_erase_FRS_CALLBACK)(sensor_meta* sensor, uint16_t frs_type, int cmock_num_calls);
void erase_FRS_AddCallback(CMOCK_erase_FRS_CALLBACK Callback);
void erase_FRS_Stub(CMOCK_erase_FRS_CALLBACK Callback);
#define erase_FRS_StubWithCallback erase_FRS_Stub
int erase_FRS_CallCount(void);
#define parse_InputReport_Ignore() TEST_FAIL_MESSAGE("parse_InputReport requires _IgnoreAndReturn");
#define parse_InputReport_IgnoreAndReturn(cmock_retval) parse_InputReport_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void parse_InputReport_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define parse_InputReport_StopIgnore() parse_InputReport_CMockStopIgnore()
void parse_InputReport_CMockStopIgnore(void);
#define parse_InputReport_Expect(sensor) TEST_FAIL_MESSAGE("parse_InputReport requires _ExpectAndReturn");
#define parse_InputReport_ExpectAndReturn(sensor, cmock_retval) parse_InputReport_CMockExpectAndReturn(__LINE__, sensor, cmock_retval)
void parse_InputReport_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sensor_meta* sensor, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_parse_InputReport_CALLBACK)(sensor_meta* sensor, int cmock_num_calls);
void parse_InputReport_AddCallback(CMOCK_parse_InputReport_CALLBACK Callback);
void parse_InputReport_Stub(CMOCK_parse_InputReport_CALLBACK Callback);
#define parse_InputReport_StubWithCallback parse_InputReport_Stub
int parse_InputReport_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
